version: '3.7'

# volumes:
#   mysql_data: {}
#   tomcat_webapps: {}

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    container_name: nginx
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - /var/log/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: curl --fail -s http://127.0.0.1:80 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    # depends_on:
    #   - tomcat8
# networks:
#   default:
#    external:
#     name: production_network # use existing network
